var res = {
  title: "MINAR RAHMAN | JHOOM  | Official Video | Bangla New Song",
  url: "https://www.youtube.com/watch?v=RWnFowWtT78",
  available: [
    {
      media: "a",
      formatType: "alone",
      itags: 251,
      ext: "webm",
      spec: {
        approxDurationMs: "273021",
        audioBitrate: 160,
        audioCodec: "opus",
        videoCodec: null,
        container: "webm",
        contentLength: "4701878",
        hasAudio: true,
        hasVideo: false,
        itag: 251,
      },
    },
    {
      media: "a",
      formatType: "alone",
      itags: 140,
      ext: "mp4",
      spec: {
        approxDurationMs: "273066",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: null,
        container: "mp4",
        contentLength: "4420151",
        hasAudio: true,
        hasVideo: false,
        itag: 140,
      },
    },
    {
      media: "a",
      formatType: "alone",
      itags: 250,
      ext: "webm",
      spec: {
        approxDurationMs: "273021",
        audioBitrate: 64,
        audioCodec: "opus",
        videoCodec: null,
        container: "webm",
        contentLength: "2384595",
        hasAudio: true,
        hasVideo: false,
        itag: 250,
      },
    },
    {
      media: "a",
      formatType: "alone",
      itags: 249,
      ext: "webm",
      spec: {
        approxDurationMs: "273021",
        audioBitrate: 48,
        audioCodec: "opus",
        videoCodec: null,
        container: "webm",
        contentLength: "1799655",
        hasAudio: true,
        hasVideo: false,
        itag: 249,
      },
    },
    {
      media: "v",
      formatType: "alone",
      itags: 18,
      ext: "mp4",
      spec: {
        approxDurationMs: "273066",
        audioBitrate: 96,
        audioCodec: "mp4a.40.2",
        videoCodec: "avc1.42001E",
        container: "mp4",
        contentLength: "18877609",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        itag: 18,
        height: 360,
        width: 640,
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [137, 140],
      ext: "mp4",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "avc1.640028",
        container: "mp4",
        contentLength: "77394815",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 1080,
        width: 1920,
        itag: [137, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [248, 251],
      ext: "webm",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 160,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "47284532",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 1080,
        width: 1920,
        itag: [248, 251],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [248, 250],
      ext: "webm",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 64,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "44967249",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 1080,
        width: 1920,
        itag: [248, 250],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [248, 249],
      ext: "webm",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 48,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "44382309",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 1080,
        width: 1920,
        itag: [248, 249],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [399, 140],
      ext: "mp4",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "av01.0.08M.08",
        container: "mp4",
        contentLength: "39425780",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 1080,
        width: 1920,
        itag: [399, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [136, 140],
      ext: "mp4",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "avc1.4d401f",
        container: "mp4",
        contentLength: "23729456",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 720,
        width: 1280,
        itag: [136, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [247, 251],
      ext: "webm",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 160,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "24814077",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 720,
        width: 1280,
        itag: [247, 251],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [247, 250],
      ext: "webm",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 64,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "22496794",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 720,
        width: 1280,
        itag: [247, 250],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [247, 249],
      ext: "webm",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 48,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "21911854",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 720,
        width: 1280,
        itag: [247, 249],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [398, 140],
      ext: "mp4",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "av01.0.05M.08",
        container: "mp4",
        contentLength: "23879130",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 720,
        width: 1280,
        itag: [398, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [135, 140],
      ext: "mp4",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "avc1.4d401e",
        container: "mp4",
        contentLength: "14655528",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 480,
        width: 854,
        itag: [135, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [244, 251],
      ext: "webm",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 160,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "16968077",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 480,
        width: 854,
        itag: [244, 251],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [244, 250],
      ext: "webm",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 64,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "14650794",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 480,
        width: 854,
        itag: [244, 250],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [244, 249],
      ext: "webm",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 48,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "14065854",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 480,
        width: 854,
        itag: [244, 249],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [397, 140],
      ext: "mp4",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "av01.0.04M.08",
        container: "mp4",
        contentLength: "15014726",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 480,
        width: 854,
        itag: [397, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [134, 140],
      ext: "mp4",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "avc1.4d401e",
        container: "mp4",
        contentLength: "10959304",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 360,
        width: 640,
        itag: [134, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [243, 251],
      ext: "webm",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 160,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "12966383",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 360,
        width: 640,
        itag: [243, 251],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [243, 250],
      ext: "webm",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 64,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "10649100",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 360,
        width: 640,
        itag: [243, 250],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [243, 249],
      ext: "webm",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 48,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "10064160",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 360,
        width: 640,
        itag: [243, 249],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [396, 140],
      ext: "mp4",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "av01.0.01M.08",
        container: "mp4",
        contentLength: "10943554",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 360,
        width: 640,
        itag: [396, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [242, 251],
      ext: "webm",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 160,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "9374181",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 240,
        width: 426,
        itag: [242, 251],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [242, 250],
      ext: "webm",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 64,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "7056898",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 240,
        width: 426,
        itag: [242, 250],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [242, 249],
      ext: "webm",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 48,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "6471958",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 240,
        width: 426,
        itag: [242, 249],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [133, 140],
      ext: "mp4",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "avc1.4d4015",
        container: "mp4",
        contentLength: "7871936",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 240,
        width: 426,
        itag: [133, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [395, 140],
      ext: "mp4",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "av01.0.00M.08",
        container: "mp4",
        contentLength: "7801533",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 240,
        width: 426,
        itag: [395, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [160, 140],
      ext: "mp4",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "avc1.4d400c",
        container: "mp4",
        contentLength: "6412544",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 144,
        width: 256,
        itag: [160, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [278, 251],
      ext: "webm",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 160,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "7690332",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 144,
        width: 256,
        itag: [278, 251],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [278, 250],
      ext: "webm",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 64,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "5373049",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 144,
        width: 256,
        itag: [278, 250],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [278, 249],
      ext: "webm",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 48,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "4788109",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 144,
        width: 256,
        itag: [278, 249],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [394, 140],
      ext: "mp4",
      spec: {
        approxDurationMs: "273000",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "av01.0.00M.08",
        container: "mp4",
        contentLength: "6416869",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 144,
        width: 256,
        itag: [394, 140],
      },
    },
  ],
}
