import { resolvedFormats } from "@/global";

var off : resolvedFormats = {
  title: "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
  url: "https://www.youtube.com/watch?v=e8eSfqaaGXQ&pp=ygUUbWluYXIga2Fyb25lIG9rYXJvbmU%3D",
  available: [
    {
      media: "a",
      formatType: "alone",
      itags: 251,
      ext: "webm",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316661",
        audioBitrate: 160,
        audioCodec: "opus",
        videoCodec: null,
        container: "webm",
        contentLength: "5345942",
        hasAudio: true,
        hasVideo: false,
        itag: 251,
      },
    },
    {
      media: "a",
      formatType: "alone",
      itags: 140,
      ext: "mp4",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316696",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: null,
        container: "mp4",
        contentLength: "5126548",
        hasAudio: true,
        hasVideo: false,
        itag: 140,
      },
    },
    {
      media: "a",
      formatType: "alone",
      itags: 250,
      ext: "webm",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316661",
        audioBitrate: 64,
        audioCodec: "opus",
        videoCodec: null,
        container: "webm",
        contentLength: "2730040",
        hasAudio: true,
        hasVideo: false,
        itag: 250,
      },
    },
    {
      media: "a",
      formatType: "alone",
      itags: 249,
      ext: "webm",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316661",
        audioBitrate: 48,
        audioCodec: "opus",
        videoCodec: null,
        container: "webm",
        contentLength: "2066062",
        hasAudio: true,
        hasVideo: false,
        itag: 249,
      },
    },
    {
      media: "v",
      formatType: "alone",
      itags: 18,
      ext: "mp4",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316696",
        audioBitrate: 96,
        audioCodec: "mp4a.40.2",
        videoCodec: "avc1.42001E",
        container: "mp4",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        itag: 18,
        height: 360,
        width: 640,
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [137, 140],
      ext: "mp4",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "avc1.640028",
        container: "mp4",
        contentLength: "56247669",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 1080,
        width: 1920,
        itag: [137, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [248, 251],
      ext: "webm",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 160,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "39148918",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 1080,
        width: 1920,
        itag: [248, 251],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [248, 250],
      ext: "webm",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 64,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "36533016",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 1080,
        width: 1920,
        itag: [248, 250],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [248, 249],
      ext: "webm",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 48,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "35869038",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 1080,
        width: 1920,
        itag: [248, 249],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [399, 140],
      ext: "mp4",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "av01.0.08M.08",
        container: "mp4",
        contentLength: "31231690",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 1080,
        width: 1920,
        itag: [399, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [398, 140],
      ext: "mp4",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "av01.0.05M.08",
        container: "mp4",
        contentLength: "20547974",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 720,
        width: 1280,
        itag: [398, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [247, 251],
      ext: "webm",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 160,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "19233975",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 720,
        width: 1280,
        itag: [247, 251],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [247, 250],
      ext: "webm",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 64,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "16618073",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 720,
        width: 1280,
        itag: [247, 250],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [247, 249],
      ext: "webm",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 48,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "15954095",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 720,
        width: 1280,
        itag: [247, 249],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [136, 140],
      ext: "mp4",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "avc1.4d401f",
        container: "mp4",
        contentLength: "19166773",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 720,
        width: 1280,
        itag: [136, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [244, 251],
      ext: "webm",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 160,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "14858524",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 480,
        width: 854,
        itag: [244, 251],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [244, 250],
      ext: "webm",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 64,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "12242622",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 480,
        width: 854,
        itag: [244, 250],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [244, 249],
      ext: "webm",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 48,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "11578644",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 480,
        width: 854,
        itag: [244, 249],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [397, 140],
      ext: "mp4",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "av01.0.04M.08",
        container: "mp4",
        contentLength: "13825625",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 480,
        width: 854,
        itag: [397, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [135, 140],
      ext: "mp4",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "avc1.4d401e",
        container: "mp4",
        contentLength: "12670570",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 480,
        width: 854,
        itag: [135, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [243, 251],
      ext: "webm",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 160,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "12137571",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 360,
        width: 640,
        itag: [243, 251],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [243, 250],
      ext: "webm",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 64,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "9521669",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 360,
        width: 640,
        itag: [243, 250],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [243, 249],
      ext: "webm",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 48,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "8857691",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 360,
        width: 640,
        itag: [243, 249],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [396, 140],
      ext: "mp4",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "av01.0.01M.08",
        container: "mp4",
        contentLength: "10480380",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 360,
        width: 640,
        itag: [396, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [134, 140],
      ext: "mp4",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "avc1.4d401e",
        container: "mp4",
        contentLength: "10106838",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 360,
        width: 640,
        itag: [134, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [242, 251],
      ext: "webm",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 160,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "9262626",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 240,
        width: 426,
        itag: [242, 251],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [242, 250],
      ext: "webm",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 64,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "6646724",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 240,
        width: 426,
        itag: [242, 250],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [242, 249],
      ext: "webm",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 48,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "5982746",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 240,
        width: 426,
        itag: [242, 249],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [395, 140],
      ext: "mp4",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "av01.0.00M.08",
        container: "mp4",
        contentLength: "8191471",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 240,
        width: 426,
        itag: [395, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [133, 140],
      ext: "mp4",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "avc1.4d4015",
        container: "mp4",
        contentLength: "7945016",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 240,
        width: 426,
        itag: [133, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [278, 251],
      ext: "webm",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 160,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "8619611",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 144,
        width: 256,
        itag: [278, 251],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [278, 250],
      ext: "webm",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 64,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "6003709",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 144,
        width: 256,
        itag: [278, 250],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [278, 249],
      ext: "webm",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 48,
        audioCodec: "opus",
        videoCodec: "vp9",
        container: "webm",
        contentLength: "5339731",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 144,
        width: 256,
        itag: [278, 249],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [160, 140],
      ext: "mp4",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "avc1.4d400c",
        container: "mp4",
        contentLength: "6846285",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 144,
        width: 256,
        itag: [160, 140],
      },
    },
    {
      media: "v",
      formatType: "not alone",
      itags: [394, 140],
      ext: "mp4",
      title:
        "Karone Okarone | Minar Rahman | Official Music Video | Eagle Music",
      spec: {
        approxDurationMs: "316640",
        audioBitrate: 128,
        audioCodec: "mp4a.40.2",
        videoCodec: "av01.0.00M.08",
        container: "mp4",
        contentLength: "7291112",
        fps: 25,
        hasAudio: true,
        hasVideo: true,
        height: 144,
        width: 256,
        itag: [394, 140],
      },
    },
  ],
};

export {off}